saved_processes:
- Memory Compression
- System Idle Process
- smss.exe
- System
- LsaIso.exe
- ibtsiva.exe
- wininit.exe
- cncmd.exe
- wlanext.exe
- atiesrxx.exe
- unsecapp.exe
- amdfendrsr.exe
- TrustedInstaller.exe
- FMService64.exe
- ChsIME.exe
- tasklist.exe
- services.exe
- AggregatorHost.exe
- SecurityHealthSystray.exe
- csrss.exe
- WUDFHost.exe
- HPAudioAnalytics.exe
- SECOCL64.exe
- logi_lamparray_service.exe
- winlogon.exe
- NisSrv.exe
- SECOMN64.exe
- NetworkCap.exe
- LanWlanWwanSwitchingServiceUWP.exe
- AppHelperCap.exe
- taskhostw.exe
- atieclxx.exe
- spoolsv.exe
- fontdrvhost.exe
- SystemSettings.exe
- SecurityHealthService.exe
- cmd.exe
- SearchIndexer.exe
- MpDefenderCoreService.exe
- lsass.exe
- BridgeCommunication.exe
- WmiPrvSE.exe
- DiagsCap.exe
- conhost.exe
- HotKeyServiceUWP.exe
- audiodg.exe
- sihost.exe
- ShellHost.exe
- ApplicationFrameHost.exe
- RtkAudUService64.exe
- CrossDeviceResume.exe
- Registry
- OfficeClickToRun.exe
- Secure System
- ctfmon.exe
- RadeonSoftware.exe
- TouchpointAnalyticsClientService.exe
- ShellExperienceHost.exe
- dwm.exe
- RuntimeBroker.exe
- AMDRSServ.exe
- TextInputHost.exe
- python.exe
- AMDRSSrcExt.exe
- SearchHost.exe
- StartMenuExperienceHost.exe
- Taskmgr.exe
- explorer.exe
- SysInfoCap.exe
- MsMpEng.exe
- msedgewebview2.exe
- msedge.exe
- svchost.exe
- Cursor.exe
