saved_processes:
- ChsIME.exe
- ShellHost.exe
- SearchHost.exe
- QMEMGSvc.exe
- RtkAudUService64.exe
- SmartVPN.exe
- sunlogin_guard.exe
- dasHost.exe
- SearchIndexer.exe
- Taskmgr.exe
- iOAEntBiz.exe
- RstMwService.exe
- SMSvcHost.exe
- Registry
- SearchProtocolHost.exe
- System Idle Process
- WMIRegistrationService.exe
- sihost.exe
- Memory Compression
- WavesAudioService.exe
- StartMenuExperienceHost.exe
- TextInputHost.exe
- python.exe
- SecurityHealthService.exe
- NVDisplay.Container.exe
- taskhostw.exe
- mqsvc.exe
- audiodg.exe
- msedgewebview2.exe
- backgroundTaskHost.exe
- sssync.exe
- QcomWlanSrvx64.exe
- QQPCRTP.exe
- WavesSysSvc64.exe
- qmbsrv.exe
- ShellExperienceHost.exe
- jhi_service.exe
- Secure System
- AggregatorHost.exe
- LogonUI.exe
- RuntimeBroker.exe
- cpolar.exe
- AdminService.exe
- dllhost.exe
- Cursor.exe
- SecurityHealthSystray.exe
- cmd.exe
- tasklist.exe
- unsecapp.exe
- senseshield.exe
- WUDFHost.exe
- LsaIso.exe
- ApplicationFrameHost.exe
- TOfficeOperation.exe
- ss_monitor.exe
- WmiPrvSE.exe
- fontdrvhost.exe
- winrdlv3.exe
- virboxlcc.exe
