saved_processes:
- System Idle Process
- System
- Secure System
- Registry
- smss.exe
- csrss.exe
- wininit.exe
- winlogon.exe
- services.exe
- LsaIso.exe
- lsass.exe
- svchost.exe
- WUDFHost.exe
- fontdrvhost.exe
- dwm.exe
- Memory Compression
- DiagsCap.exe
- SysInfoCap.exe
- NetworkCap.exe
- unsecapp.exe
- WmiPrvSE.exe
- spoolsv.exe
- wlanext.exe
- FMService64.exe
- ibtsiva.exe
- MpDefenderCoreService.exe
- logi_lamparray_service.exe
- RtkAudUService64.exe
- SECOMN64.exe
- MsMpEng.exe
- AggregatorHost.exe
- NisSrv.exe
- SearchIndexer.exe
- ctfmon.exe
- SecurityHealthService.exe
- taskhostw.exe
- ShellHost.exe
- sihost.exe
- explorer.exe
- ShellExperienceHost.exe
- StartMenuExperienceHost.exe
- RuntimeBroker.exe
- dllhost.exe
- ChsIME.exe
- SECOCL64.exe
- conhost.exe
- cmd.exe
- AppHelperCap.exe
- OfficeClickToRun.exe
- TextInputHost.exe
- HPAudioAnalytics.exe
- HotKeyServiceUWP.exe
- LanWlanWwanSwitchingServiceUWP.exe
- ApplicationFrameHost.exe
- SystemSettings.exe
- smartscreen.exe
- chrome.exe
- Cursor.exe
- python.exe
- tasklist.exe
