saved_processes:
- FlutterPlugins.exe
- SearchHost.exe
- crashpad_handler.exe
- SecurityHealthSystray.exe
- unsecapp.exe
- WXDrive_x64.exe
- ApplicationFrameHost.exe
- WmiPrvSE.exe
- python.exe
- senseshield.exe
- Memory Compression
- ChsIME.exe
- TextInputHost.exe
- dasHost.exe
- RstMwService.exe
- LogonUI.exe
- NVDisplay.Container.exe
- wpscloudsvr.exe
- sssync.exe
- AdminService.exe
- WXWorkWeb.exe
- Widgets.exe
- sunlogin_guard.exe
- WMIRegistrationService.exe
- Cursor.exe
- SMSvcHost.exe
- WavesSysSvc64.exe
- WXWork.exe
- ShellExperienceHost.exe
- UserOOBEBroker.exe
- virboxlcc.exe
- QQPCRTP.exe
- iOAEntBiz.exe
- Registry
- msedgewebview2.exe
- qmbsrv.exe
- AggregatorHost.exe
- Secure System
- LsaIso.exe
- QcomWlanSrvx64.exe
- SecurityHealthService.exe
- taskhostw.exe
- QMEMGSvc.exe
- WavesAudioService.exe
- winrdlv3.exe
- SmartVPN.exe
- tasklist.exe
- WUDFHost.exe
- WeChatAppEx.exe
- sihost.exe
- RtkAudUService64.exe
- ss_monitor.exe
- mqsvc.exe
- wpscenter.exe
- fontdrvhost.exe
- SearchIndexer.exe
- StartMenuExperienceHost.exe
- WeMail.exe
- dllhost.exe
- System Idle Process
- TOfficeOperation.exe
- RuntimeBroker.exe
- cpolar.exe
- ShellHost.exe
- WidgetService.exe
- smartscreen.exe
- wslservice.exe
- cmd.exe
- jhi_service.exe
- PushNotificationsLongRunningTask.exe
